---
- name: Remove containerd (Ubuntu) 
  ansible.builtin.apt:
    name: 
      - containerd 
    state: present
    update_cache: true
  become: true


- name: Install containerd.io
  ansible.builtin.apt:
    name: containerd.io
    state: present
    update_cache: true
  become: true

- name: Create /etc/containerd directory
  ansible.builtin.file:
    path: /etc/containerd
    state: directory
  become:

- name: Copy containerd template 
  template:
    src: config.j2
    dest: /etc/containerd/config.toml
    owner: root
    group: root
    mode: '0644'
  become: true

# - name: Write containerd CRI configuration
#   copy:
#     dest: /etc/containerd/config.toml
#     content: |
#       [plugins."io.containerd.grpc.v1.cri"]
#         systemd_cgroup = true
#         sandbox_image = "registry.k8s.io/pause:3.10"  
#     owner: root
#     group: root
#     mode: '0644'
#   become: true

- name: Configure crictl to set containerd as the default CRI
  copy:
    dest: /etc/crictl.yaml
    content: |
      runtime-endpoint: unix:///run/containerd/containerd.sock
      image-endpoint: unix:///run/containerd/containerd.sock
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Restart containerd service
  ansible.builtin.systemd:
    name: containerd
    state: restarted
    enabled: true
  become: true

  