---
- hosts: proxmox
  become: true
  vars_files: "{{ playbook_dir }}/proxmox-temp-conf.yml" 
  vars_prompt:
    - name: password
      prompt: "Terraform passowrd:" 
  tasks:

    - name: Create a new Role for Terraform
      shell: |
        pveum role add TerraformProv -privs "Datastore.AllocateSpace Datastore.Audit Pool.Allocate Sys.Audit Sys.Console Sys.Modify VM.Allocate VM.Audit VM.Clone VM.Config.CDROM VM.Config.Cloudinit VM.Config.CPU VM.Config.Disk VM.Config.HWType VM.Config.Memory VM.Config.Network VM.Config.Options VM.Migrate VM.Monitor VM.PowerMgmt"

    - name: Add user Terraform with password prompted
      shell: |
        pveum user add terraform-prov@pve --password {{password}}

    - name: Add the TERRAFORM-PROV role to the terraform-prov user
      shell: |
        pveum user add terraform-prov@pve --password {{password}}
      