---
- name: Check if Swarm has already been initialized
  ansible.builtin.command: docker node ls
  register: swarm_status
  ignore_errors: true

- name: Initialize new Docker Swarm Leader
  ansible.builtin.command: docker swarm init --advertise-addr={{ inventory_hostname }}
  run_once: true

- name: Get the Manager join-token
  ansible.builtin.command: docker swarm join-token --quiet manager
  register: manager_token

- name: Get the worker join-token
  ansible.builtin.command: docker swarm join-token --quiet worker
  register: worker_token
