---
# Swap needs to be disabled for the kubelet to work properly 
# This role ensures that through various ways.

- name: Remove swap entry from /etc/fstab
  lineinfile:
    path: /etc/fstab
    regexp: '^/swap.img'
    line: '#/swap.img'
    state: absent
  become: true

- name: Disable swap through CLI (swapoff)
  become: true
  shell: "swapoff --all" 

- name: Disable swap through CLI, (/etc/sysctl.conf)
  become: true
  lineinfile: 
    path: /etc/sysctl.conf
    insertafter: EOF 
    line: vm.swapiness = 0