---
- name: Download Flannel manifest
  get_url:
    url: https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml
    dest: "/tmp/kube-flannel.yml"
    mode: '0644'
  when: inventory_hostname == groups['k8s_control_planes'][0]

- name: Apply Flannel Manifest
  kubernetes.core.k8s: 
    state: present
    src: /tmp/kube-flannel.yml
  when: inventory_hostname == groups['k8s_control_planes'][0]
  any_errors_fatal: true