[all:vars]
ansible_python_interpreter=/usr/bin/python3
[pihole]
192.168.1.2
192.168.1.3
[pihole:vars]
ansible_ssh_user=pi
ansible_port=22

[swarm:children]
haproxy_swarm
swarm_managers
swarm_workers

[haproxy_swarm]
#192.168.1.135 ansible_ssh_user=swarm ansible_port=22
[swarm_managers]
192.168.1.140 ansible_ssh_user=swarm ansible_port=22
#192.168.1.141 ansible_ssh_user=swarm ansible_port=22
#192.168.1.142 ansible_ssh_user=swarm ansible_port=22
[swarm_workers]
#192.168.1.140 ansible_ssh_user=swarm ansible_port=22
#192.168.1.141 ansible_ssh_user=swarm ansible_port=22
#192.168.1.142 ansible_ssh_user=swarm ansible_port=22

[k8s:children]
k8s_control_planes
k8s_worker_nodes
haproxy_k8s

[haproxy_k8s]
192.168.1.160 ansible_ssh_user=k8s ansible_port=22
[k8s_control_planes]
192.168.1.161 ansible_ssh_user=k8s ansible_port=22
192.168.1.162 ansible_ssh_user=k8s ansible_port=22
192.168.1.163 ansible_ssh_user=k8s ansible_port=22
# 192.168.1.167 ansible_ssh_user=k8s ansible_port=22
# 192.168.1.168 ansible_ssh_user=k8s ansible_port=22
[k8s_worker_nodes]
192.168.1.164 ansible_ssh_user=k8s ansible_port=22
192.168.1.165 ansible_ssh_user=k8s ansible_port=22
192.168.1.166 ansible_ssh_user=k8s ansible_port=22

; [proxmox]
; 192.168.1.5
; 192.168.1.6
; 192.168.1.7
; [proxmox:vars]
; ansible_ssh_user=root
; [proxmox_backup_server]
; 192.168.1.40



[all:vars]
ansible_connection=ssh
device2_hdd_dev=/dev/sdb
DELAY_VAL=240
ansible_port=22
