---
- name: Upgrade all packages to the latest version
  become: true
  become_method: sudo
  ansible.builtin.apt:
    name: "*"
    state: latest
    force_apt_get: true
    update_cache: true

- name: Wait for server to restart
  become: true
  ansible.builtin.reboot:
    reboot_timeout: "{{ DELAY_VAL }}"
  ignore_errors: true
